[project]
name = "open-vis-framework-instance"
description = "Add your description here"
readme = "README.md"
version = "14.0.0"
requires-python = "~= 3.14.0"

dependencies = [
  "invenio-app-rdm[opensearch2]~=14.0.0",
  "uwsgi>=2.0",
  "uwsgitop>=0.11",
  "uwsgi-tools>=1.1.1",
  "lxml-html-clean>=0.1.1",
  "open-vis-framework",
]

[tool.uv.sources]
"open-vis-framework" = { workspace = true }

[tool.uv.workspace]
members = ["site"]

[project.optional-dependencies]
tests = [
  "pytest-invenio>=4.0.0,<5.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
bypass-selection = true
